language: ruby
rvm:
- 2.5.3
script:
- make
deploy:
- provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: www.brutalismbot.com
  local-dir: www
  acl: private
  on:
    repo: brutalismbot/brutalismbot.com
    tags: true
after_deploy:
- make apply
