version: '3'

services:

  base: &base
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
    image: lambci/lambda:build-python3.7
    volumes:
      - ./:/var/task
    working_dir: /var/task

  aws:
    <<: *base
    entrypoint: aws

  terraform:
    <<: *base
    image: hashicorp/terraform
