#!/usr/bin/env ruby
require "dotenv/load"

rum :"brutalismbot/brutalismbot.com" do
  tag %x(git describe --tags --always).strip

  env :AWS_ACCESS_KEY_ID
  env :AWS_DEFAULT_REGION
  env :AWS_SECRET_ACCESS_KEY
  env :RUBY => "2.7"
  env :TF_VAR_release => tag

  stage :build
  stage :plan => :build

  artifact "www.sha256sum" => :build

  desc "Apply infrastructure"
  run :apply => :plan

  default %w[www.sha256sum plan]
end

desc "List S3 contents"
task :ls do
  sh "aws s3 ls s3://www.brutalismbot.com/"
end

desc "Sync local files with S3"
task :sync do
  sh "aws s3 sync www s3://www.brutalismbot.com/"
end

desc "Start local HTTP server"
task :up do
  sh "ruby -run -e httpd www"
end
